In [232]:
# Siempre al principio, importamos las librerías.
import pandas as pd
import numpy as np

In [233]:
#from google.colab import drive
#drive.mount('/content/drive')

In [234]:
RUTA_GLOBAL = '.'

In [235]:
#!pip install pandas --user

## 1- Para leer el data set usamos la función de pandas read_csv

Con esta función podemos leer archivos que estén en una url pública o en una ubicación del disco accesible desde la Jupyter Notebook.

In [236]:
df = pd.read_csv(f'{RUTA_GLOBAL}/sueldo_funcionarios_2019.csv', sep=',')
df

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.80,0.00,197745.80,NaN
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.80,0.00,197745.80,NaN
2,27-24483014-0,2019,1,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,224516.62,0.00,224516.62,NaN
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.00,224516.62,NaN
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.00,224516.62,NaN
...,...,...,...,...,...,...,...,...,...,...
380,20-26735689-1,2019,12,MENDEZ,JUAN JOSE,SECR Transporte y Obras Públicas,249972.86,124986.43,374959.29,NaN
381,20-23864572-8,2019,12,STRAFACE,FERNANDO DIEGO,SECR General y Relaciones Internacionales,275089.75,137544.87,412634.62,NaN
382,20-21981279-6,2019,12,SCRENCI SILVA,BRUNO GUIDO,Ministerio de Gobierno,275089.75,137544.87,412634.62,NaN
383,20-30593774-7,2019,12,AVELLANEDA,PATRICIO IGNACIO,"SECR Planificación, Evaluación y Coordinación ...",249972.86,124986.43,374959.29,NaN
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

## 2- Consultamos las columnas

In [237]:
df.describe()

,anio,mes,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii
count,385.0,385.000000,385.000000,385.000000,385.000000
mean,2019.0,6.631169,234234.368000,20282.084883,254516.452883
std,0.0,3.539077,35043.160085,45248.840725,51434.987870
min,2019.0,1.000000,74991.860000,0.000000,185396.540000
25%,2019.0,4.000000,224516.620000,0.000000,224516.620000
50%,2019.0,7.000000,239470.360000,0.000000,245811.620000
75%,2019.0,10.000000,249972.870000,0.000000,263531.980000
max,2019.0,12.000000,275089.750000,170855.560000,445945.310000

## 3- Extraemos una muestra

In [238]:
df.sample(5) #aleatorio
df.head(5) # primeros registros
df.tail(10) #ultimos registros

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
375,27-26690980-8,2019,12,UHALDE,MARIA PAULA,SECR Transformación Cultural,249972.86,124986.43,374959.29,NaN
376,20-17735449-0,2019,12,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,245811.62,122905.81,368717.43,NaN
377,27-21759789-2,2019,12,LEGUIZAMON,ISABELLA KARINA,"Consejo de los Derechos de Niñas, Niños y Adol...",249972.86,124986.43,374959.29,NaN
378,20-22293622-6,2019,12,FERNANDEZ,DIEGO HERNAN,SECR Integración Social y Urbana,249972.86,124986.43,374959.29,NaN
379,20-16891539-0,2019,12,ROBREDO,GONZALO,Ente de Turismo Ley Nº 2627,249972.86,124986.43,374959.29,NaN
380,20-26735689-1,2019,12,MENDEZ,JUAN JOSE,SECR Transporte y Obras Públicas,249972.86,124986.43,374959.29,NaN
381,20-23864572-8,2019,12,STRAFACE,FERNANDO DIEGO,SECR General y Relaciones Internacionales,275089.75,137544.87,412634.62,NaN
382,20-21981279-6,2019,12,SCRENCI SILVA,BRUNO GUIDO,Ministerio de Gobierno,275089.75,137544.87,412634.62,NaN
383,20-30593774-7,2019,12,AVELLANEDA,PATRICIO IGNACIO,"SECR Planificación, Evaluación y Coordinación ...",249972.86,124986.43,374959.29,NaN
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

## 4- Consultamos la cantidad de filas y de columnas

In [239]:
# La propiedad shape nos devuelve una tupla (filas,columnas)
type(df.shape)

tuple

# Vectorización con Pandas

Pandas es una de las librerías de Python más usadas para análisis de datos. El nombre pandas viene de "Panel Data Analysis" y su funcionalidad permite hacer operaciones sobre datos que se encuentran en memoria de manera eficiente.

Pandas es útil para trabajar sobre datos tabulares, con dos condiciones importantes:

I. Los datos se encuentran enteramente en la memoria RAM. Con lo cual, el tamaño de los datos que podemos manipular está limitado por el hardware. Como regla de pulgar, es una buena práctica no ocupar más de 1/3 de la memoria RAM de nuestro dispositivo con el dataset. Así, si estamos trabajando localmente en una notebook con 8GB de memoria RAM no es recomendable procesar datasets de más de 2.33GB.

II. En pandas, las operaciones sobre filas y columnas son, en general, eficientes porque se hacen de forma "vectorizada". En realidad esta optimización, se hace desde numpy, una librería para realizar operaciones matemáticas que se utilizó a su vez para escribir pandas.

Las operaciones vectorizadas son las que se realizan en bloque en vez de caso por caso. Las computadoras de hoy tienen la capacidad de recibir muchas instrucciones juntas y procesar varias de ellas a la vez. Por ejemplo, si nuestro hardware tiene la capacidad de procesar 4 operaciones juntas, el resultado de vectorizar una operación matemática es el siguiente:

<img src = 'https://datasets-humai.s3.amazonaws.com/images/vectorizacion.png' />


En el primer caso hay que hacer 5 operaciones y en el segundo caso sólo dos.

Es importante entender, entonces, que Pandas trabaja de esta manera y que por eso es una de las herramientas más elegidas para manipular datos en memoria.

In [240]:
np.random.seed(1)

In [241]:
lista1 = list(np.random.randint(1, 100, 1000000))
lista2 = list(np.random.randint(1, 100, 1000000))

In [242]:
%%timeit
for x,y in zip(lista1,lista2):
    x * y

80.1 ms ± 5.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Ahora probemos hacer lo mismo con dos series de Pandas

In [243]:
serie1 = pd.Series(lista1)
serie2 = pd.Series(lista2)

In [244]:
%%timeit
resultado = serie1 * serie2

1.93 ms ± 166 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Conclusión: la operación vectorizada es <strong> más de 70 veces más rápida.</strong>

In [245]:
serie1 * serie2

0         1140
1         1105
2         5110
3          890
4         4028
          ...
999995    1128
999996    9312
999997     148
999998    2960
999999     867
Length: 1000000, dtype: int32



# Los objetos fundamentales de Pandas

## Series

Las series son "columnas" que de una tabla que están asociadas a un índice y a un nombre. Igual que una lista común de Python es una secuencia de elementos ordenados, pero a diferencia de la lista está asociada a más información.

In [246]:
# Las series se pueden crear a partir de una lista
serie = pd.Series(['a','b','c'], name="abc")
serie

0    a
1    b
2    c
Name: abc, dtype: object

In [247]:
# Propiedades importantes de las series
print('Tipo de objetos que tiene ', serie.dtype)
print('Nombre ', serie.name)
print('Index ',serie.index)
print('Valores ',serie.values)

Tipo de objetos que tiene  object
Nombre  abc
Index  RangeIndex(start=0, stop=3, step=1)
Valores  ['a' 'b' 'c']

## DataFrames

Los DataFrames son "tablas", compuestas por varias "columnas" o series que comparten todas un mismo índice. En general los DataFrames se crean a partir de leer tablas de archivos (pueden ser en formato json o csv) pero a veces también se crean a partir de listas de diccionarios o de otras maneras.

Los DataFrames tienen un objeto Index que describe los nombres de columnas y otro objeto Index que describen los nombres de las filas.

In [248]:
# Leemos un dataset público
df = pd.read_csv(f'{RUTA_GLOBAL}/sueldo_funcionarios_2019.csv')

In [249]:
# Propiedades importantes de los dataframes
print('Columnas ', df.columns)
print('Index ', df.index)
print('Dimensiones ',df.shape)

Columnas  Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')
Index  RangeIndex(start=0, stop=385, step=1)
Dimensiones  (385, 10)

In [250]:
# Consultar las primeras filas
df.head(3)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.80,0.0,197745.80,NaN
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.80,0.0,197745.80,NaN
2,27-24483014-0,2019,1,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,224516.62,0.0,224516.62,NaN

Si queremos extraer una serie del DataFrame, podemos hacerlo de la misma forma en que extraemos un valor de un diccionario.

In [251]:
#Valores únicos  de la serie
df['mes'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [252]:
df.head(2)

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
0,20-17692128-6,2019,1,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,197745.8,0.0,197745.8,NaN
1,20-17735449-0,2019,1,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,197745.8,0.0,197745.8,NaN

In [253]:
serie_mes = df['mes']

In [254]:
type(serie_mes)

pandas.core.series.Series

## Índices

Los índices acompañan a las series y a los Data Frames. Son conjuntos ordenados e inmutables de elementos

In [255]:
#Obtener el rango de index generado en el DataFrame
df.index

RangeIndex(start=0, stop=385, step=1)

In [256]:
#indice de las series
df.columns

Index(['cuil', 'anio', 'mes', 'funcionario_apellido', 'funcionario_nombre',
       'reparticion', 'asignacion_por_cargo_i', 'aguinaldo_ii',
       'total_salario_bruto_i_+_ii', 'observaciones'],
      dtype='object')

In [257]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [258]:
#ind[2] = 0

---
Ejercicio: exploren el dataset público que se encuentra en la siguiente url: https://datasets-humai.s3.amazonaws.com/datasets/titanic.csv ¿De qué se trata? ¿Cuántas filas tiene? ¿Cuántas columnas? Al leerlo, pueden almacenarlo en la variable df_titanic.

In [259]:
df_titanic = pd.read_csv(f'{RUTA_GLOBAL}/titanic.csv'
                         ,sep='|'
                        )

In [260]:
df_titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [261]:
df_titanic.shape

(891, 12)

In [262]:
df_titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

---
## Filtrando un DataFrame (Indexing)

Hay muchas técnicas para filtrar un DataFrame. Podemos querer filtrar por columnas o por filas, por posición o por nombre. También podemos querer filtrar por condiciones que se cumplen o no. Cuando no queremos filtrar sobre una dimensión (filas o columnas) usamos ":" para seleccionar todo.

<center>

<img src='img/indexing.png' style='height:350px' />

</center>

### Boolean Indexing

Supongamos que queremos tomar el dataset de funcionarios y quedarnos únicamente con los que pertenecen al Ministerio de Cultura.
Para eso lo que hacemos es indexar al DataFrame por una condición booleana. Eso implica que debemos crear una serie compuesta por valores True y False para aplicarla como índice a las filas.

Los operadores que sirven para evaluar condiciones sobre las series son:

<center>

| S  | Descripción   | S  | Descripción   |   |
|----|---------------|----|---------------|---|
| >= | Mayor o Igual | <= | Menor o Igual |   |
| == | Igual         | != | Distinto      |   |
| >  | Mayor         | <  | Menor         |   |

#### Máscara booleana

Veamos lo que pasa cuando le aplicamos a una serie una condición que devuelve un booleano

In [263]:
## devuelve una Serie de valores booleanos
df['anio'] != 2019

0      False
1      False
2      False
3      False
4      False
       ...
380    False
381    False
382    False
383    False
384    False
Name: anio, Length: 385, dtype: bool

In [264]:
mascara_booleana = df['anio'] != 2019

Nos devuelve una serie de la misma longitud que la original y que contiene sólo valores True o False.

In [265]:
## tipo de la variable
type(mascara_booleana)

pandas.core.series.Series

In [266]:
mascara_booleana.shape

(385,)

In [267]:
## tipo de los datos dentro de la Serie
mascara_booleana.dtype

dtype('bool')

Ahora seleccionemos, los registros que corresponden al Ministerio de Cultura.

In [268]:
#Aplicamos el filtro al DataFrame
df_min_cul = df.loc[df['reparticion'] == 'Ministerio de Cultura', :]

In [269]:
# Veamos la cantidad de casos
df_min_cul.shape

(12, 10)

Algo que puede llegar a confundir sobre el Indexing en Pandas es que en algunos casos se puede ser menos explícito a la hora de filtrar. Por ejemplo si ponemos una condición Booleana, pandas asume que el tipo de indexing es loc y que el filtro es sobre las filas y no sobre las columnas:

In [270]:
#si ponemos una condición Booleana, pandas asume que el tipo de indexing es loc y que el filtro es sobre las filas y no sobre las columnas
df_min_cul = df[df['reparticion'] == 'Ministerio de Cultura']
df_min_cul

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
4,20-25641207-2,2019,1,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.00,224516.62,NaN
36,20-25641207-2,2019,2,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,224516.62,0.00,224516.62,NaN
68,20-25641207-2,2019,3,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,231167.76,0.00,231167.76,NaN
99,20-25641207-2,2019,4,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.00,249661.60,NaN
130,20-25641207-2,2019,5,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.00,249661.60,NaN
161,20-25641207-2,2019,6,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,124830.80,374492.40,NaN
192,20-25641207-2,2019,7,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,263531.98,0.00,263531.98,NaN
223,20-25641207-2,2019,8,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,263531.98,0.00,263531.98,NaN
254,20-25641207-2,2019,9,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,275089.75,0.00,275089.75,NaN
285,20-25641207-2,2019,10,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,275089.75,0.00,275089.75,NaN
316,20-25641207-2,2019,11,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,275089.75,0.00,275089.75,NaN
368,20-25641207-2,2019,12,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,275089.75,137544.87,412634.62,NaN

In [271]:
df_min_cul.shape

(12, 10)

---
Ejercicio 2: Volviendo al DataFrame del Titanic ¿Cuántos pasajeros sobrevivieron y cuántos no? ¿Cuántos pagaron una tarifa menor a 25?

In [272]:
df_titanic = pd.read_csv(f'{RUTA_GLOBAL}/titanic.csv',sep='|')
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [273]:
#Solución
df_titanic[df_titanic['Survived']==1].count()

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [274]:
df_titanic[df_titanic['Survived']==0].shape

(549, 12)

In [275]:
df_titanic.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [276]:
df_titanic[df_titanic['Fare'] < 25].shape

(557, 12)

---

#### Máscara booleana con muchas condiciones

Ahora tratemos de filtrar el dataset por dos condiciones: por ejemplo tomar los sueldos de abril de la secretaria de innovación.
Para eso tenemos que combinar dos máscaras booleanas con una condición.
<center>

| S | Descripcion        | S  | Descripcion |   |
|---|--------------------|----|-------------|---|
| & | AND (y)            | \| | OR (o)      |   |
| ^ | XOR (o exclusivo)  | ~  | NOT (no)    |   |

</center>

Por ejemplo: seleccionemos los casos donde o bien se haya cobrado aguinaldo o bien el salario total haya sido mayor que 240.000, pero no las dos cosas.

In [277]:
#Por ejemplo: seleccionemos los casos donde o bien se haya cobrado aguinaldo o bien el salario total haya sido mayor que 240.000, pero no las dos cosas.
df[(df['total_salario_bruto_i_+_ii'] > 240000) ^ (df['aguinaldo_ii'] > 0)]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019
97,27-24483014-0,2019,4,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,249661.60,0.00,249661.60,NaN
98,20-13872301-2,2019,4,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
99,20-25641207-2,2019,4,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,249661.60,0.00,249661.60,NaN
100,27-13221055-7,2019,4,BOU PEREZ,ANA MARIA,Ministerio de Salud,249661.60,0.00,249661.60,NaN
...,...,...,...,...,...,...,...,...,...,...
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12
361,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SECR de Medios,187539.45,15628.29,203167.74,alta desde el 10/12
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12
363,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,187539.45,15628.29,203167.74,alta desde el 10/12
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

Ahora veamos los sueldos de febrero de la SECR Ciencia, Tecnologia e Innovacion.

In [278]:
df[(df['mes'] == 2) & (df['reparticion'] == 'SECR Ciencia, Tecnologia e Innovacion')]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019

### Boolean indexing con query()

La sintaxis que se utiliza para hacer Boolean indexing es un poco repetitiva. Noten que filtrar (aún en su expresión más corta sin loc ni especificar filas o columnas) implica ESCRIBIR DOS VECES el nombre del dataset. Para crear un shortcut, Pandas ofrece la función .query()

In [279]:
#Filtrado con comillas simples, la cual implica que la instruccion debe ser esctria en una sola linea
df_cult = df.query('reparticion == "Ministerio de Cultura"')

También se puede hacer query sobre múltiples condiciones.

In [280]:
#Tambien podemos colocar multiples condiciones y si a ello le agregamos 3 comillas al inicio y final, se puede escribir el filtro en más de una linea
df2 = df.query('''asignacion_por_cargo_i > 240000  & aguinaldo_ii > 0''')

In [281]:
df2.shape

(34, 10)

Ejercicio: Piensen cómo traducir a la sintaxis de query, estas consultas que ya hicimos:

In [282]:
# df_sem2 = df[df['mes'] > 6]
# Solución
df_sem2 = df.query('mes > 6')
df_sem2

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
188,20-17692128-6,2019,7,RODRIGUEZ LARRETA,HORACIO ANTONIO,Jefe de Gobierno,228396.40,0.00,228396.40,NaN
189,20-17735449-0,2019,7,SANTILLI,DIEGO CESAR,Vicejefatura de Gobierno,228396.40,0.00,228396.40,NaN
190,27-24483014-0,2019,7,ACUÑA,MARIA SOLEDAD,Ministerio de Educación e Innovación,263531.98,0.00,263531.98,NaN
191,20-13872301-2,2019,7,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.00,263531.98,NaN
192,20-25641207-2,2019,7,AVOGADRO,ENRIQUE LUIS,Ministerio de Cultura,263531.98,0.00,263531.98,NaN
...,...,...,...,...,...,...,...,...,...,...
380,20-26735689-1,2019,12,MENDEZ,JUAN JOSE,SECR Transporte y Obras Públicas,249972.86,124986.43,374959.29,NaN
381,20-23864572-8,2019,12,STRAFACE,FERNANDO DIEGO,SECR General y Relaciones Internacionales,275089.75,137544.87,412634.62,NaN
382,20-21981279-6,2019,12,SCRENCI SILVA,BRUNO GUIDO,Ministerio de Gobierno,275089.75,137544.87,412634.62,NaN
383,20-30593774-7,2019,12,AVELLANEDA,PATRICIO IGNACIO,"SECR Planificación, Evaluación y Coordinación ...",249972.86,124986.43,374959.29,NaN
384,27-27011181-0,2019,12,FERNANDEZ,KARINA BEATRIZ,SECR Asuntos Estratégicos,187539.45,15628.29,203167.74,alta desde el 10/12

In [283]:
# df[(df['mes'] == 2) & (df['reparticion'] == 'SECR Ciencia, Tecnologia e Innovacion')]
# Solución
df.query('(mes == 2) & (reparticion == "SECR Ciencia, Tecnologia e Innovacion")')

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
55,20-26781618-3,2019,2,LARRE,PEDRO ANDRES,"SECR Ciencia, Tecnologia e Innovacion",204017.27,34002.88,238020.15,baja 28/2/2019

### Fancy Indexing

Ahora vamos a quedarnos con un subconjunto de columnas del DataFrame.

Existe una forma menos explícita de hacer esta misma operación. Si pasamos una lista al indexing, pandas asume que el tipo de indexing es loc y que el filtro es sobre las columnas y no las filas:

In [284]:
#Si pasamos una lista al indexing, pandas asume que el tipo de indexing es loc y que el filtro es sobre las columnas y no las filas:
COL = ['anio','mes']
df[COL]

     anio  mes
0    2019    1
1    2019    1
2    2019    1
3    2019    1
4    2019    1
..    ...  ...
380  2019   12
381  2019   12
382  2019   12
383  2019   12
384  2019   12

[385 rows x 2 columns]

Fíjense lo que pasa si tratamos de acceder a filas utilizando una lista de nombres, en este caso [0,1].

In [285]:
# Incorrecto
#df_view = df[:,[0,1]]

Nos da un error porque cuando pasamos únicamente una lista al indexing, pandas asume que queremos un set de columnas y si los nombres no existen, da error. La forma correcta de hacerlo es pasar una lista de índices y explicitar que vamos a indizar con loc y que seleccionamos todas las columnas.

In [286]:
# Correcto
df_view = df.loc[[3,8],:]

In [287]:
df_view

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.0,224516.62,NaN
8,20-22293873-3,2019,1,MIGUEL,FELIPE OSCAR,Jefatura de Gabinete de Ministros,224516.62,0.0,224516.62,NaN

---
Ejercicio. Volviendo al ejemplo del titanic...

1) ¿Cuántos hombres y mujeres sobrevivieron?

2) ¿Cuántos menores de 18 años había? ¿Cuántos sobrevivieron?

3) Seleccionen únicamente las columnas Sex y Survived y almacenenlas en un nuevo DataFrame que se llame df_titanic_subset.

In [288]:
df_titanic.query('Sex == "male" & Survived==1').shape
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [289]:
df_titanic.query('Sex == "female" & Survived==1').shape

(233, 12)

In [290]:
df_titanic.query('Age <= 18').shape

(139, 12)

In [291]:
df_titanic.query('Age <= 18 & Survived==1').shape

(70, 12)

In [292]:
df_titanic_subset = df_titanic[['Sex','Survived']]

In [293]:
df_titanic_subset.head()

      Sex  Survived
0    male         0
1  female         1
2  female         1
3  female         1
4    male         0

---
## Funciones de Agregación

Utilizando Pandas podemos aplicar funciones a nivel de columna. Algunas funciones predefinidas son la media, el desvío estándar y la sumatoria, el valor máximo y el mínimo.

Algunas de las funciones de agregación más comunes son:

<center>

| Nombre             | Versión que descarta NaN | Descripción                            |
|--------------------|--------------------------|----------------------------------------|
| serie.sum()        | serie.sum(skipna=True)   | Suma todos los elementos               |
| serie.prod()       | serie.prod(skipna=True)  | Multiplica                             |
| serie.mean()       | serie.mean(skipna=True)  | Promedia                               |
| serie.std()        | serie.std(skipna=True)   | Calcula el desvío estándar             |
| serie.var()        | serie.var(skipna=True)   | Calcula la varianza                    |
| serie.min()        | serie.min(skipna=True)   | Calcula el valor mínimo                |
| serie.max()        | serie.max(skipna=True)   | Calcula el valor máximo                |
| serie.argmin()     | serie.argmin(skipna=True)| Calcula el índice del valor mínimo     |
| serie.argmax()     | serie.argmax(skipna=True)| Calcula el índice del valor máximo     |
| serie.median()     | serie.median(skipna=True)| Calcula la mediana                     |
| X                  | serie.quantile()         | Calcula los percentiles                |
| serie.any()        | X                        | Evalúa si algún elemento es TRUE       |
| serie.all()        | X                        | Evalúa si todos los elementos son TRUE |

</center>

In [294]:
#Forma 1
df['mes'].max()
#df.mes.max()

12

In [295]:
#Función de agregación con filtro
df['asignacion_por_cargo_i'].mean()

234234.36800000002

In [296]:
df['asignacion_por_cargo_i'].std()

35043.160084661766

In [297]:
df['total_salario_bruto_i_+_ii'].sum()

97988834.36000001

Podemos combinar los filtros que vimos antes con las funciones de agregación para responder preguntas cómo ¿Cuál fue en gasto en asignaciones de funcionarios para la Secretaría de Medios 2019? ¿Y para la de Justicia y Seguridad?

In [298]:
df[df['reparticion'] == 'SECR de Medios']['total_salario_bruto_i_+_ii'].sum()

3232402.25

In [299]:
df[df['reparticion'] == 'SECR Justicia y Seguridad']['total_salario_bruto_i_+_ii'].sum()

3029551.7300000004

Ahora respondamos algunas preguntas: ¿Quién o quiénes del dataset cobran el salario más alto? ¿Y el más bajo?

In [300]:
df[df['total_salario_bruto_i_+_ii'] == df['total_salario_bruto_i_+_ii'].max()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [301]:
#Utilizar variables dentro de un filtro con query
x = 'ASTARLOA'
df.query('funcionario_apellido == @x' )

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.00,224516.62,NaN
35,20-13872301-2,2019,2,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.00,224516.62,NaN
67,20-13872301-2,2019,3,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,231167.76,0.00,231167.76,NaN
98,20-13872301-2,2019,4,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
129,20-13872301-2,2019,5,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
160,20-13872301-2,2019,6,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,165196.76,414858.36,NaN
191,20-13872301-2,2019,7,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.00,263531.98,NaN
222,20-13872301-2,2019,8,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.00,263531.98,NaN
253,20-13872301-2,2019,9,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,0.00,275089.75,NaN
284,20-13872301-2,2019,10,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,0.00,275089.75,NaN
315,20-13872301-2,2019,11,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,0.00,275089.75,NaN
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [302]:
df.query('funcionario_apellido == @x' )

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
3,20-13872301-2,2019,1,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.00,224516.62,NaN
35,20-13872301-2,2019,2,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,224516.62,0.00,224516.62,NaN
67,20-13872301-2,2019,3,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,231167.76,0.00,231167.76,NaN
98,20-13872301-2,2019,4,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
129,20-13872301-2,2019,5,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,0.00,249661.60,NaN
160,20-13872301-2,2019,6,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,249661.60,165196.76,414858.36,NaN
191,20-13872301-2,2019,7,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.00,263531.98,NaN
222,20-13872301-2,2019,8,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,263531.98,0.00,263531.98,NaN
253,20-13872301-2,2019,9,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,0.00,275089.75,NaN
284,20-13872301-2,2019,10,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,0.00,275089.75,NaN
315,20-13872301-2,2019,11,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,0.00,275089.75,NaN
374,20-13872301-2,2019,12,ASTARLOA,GABRIEL MARIA,Procuración General de la Ciudad de Buenos Aires,275089.75,170855.56,445945.31,NaN

In [303]:
df[df['total_salario_bruto_i_+_ii'] == df['total_salario_bruto_i_+_ii'].min()]

,cuil,anio,mes,funcionario_apellido,funcionario_nombre,reparticion,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii,observaciones
344,27-30744939-6,2019,12,FERRERO,GENOVEVA,SECR Administración de Seguridad y Emergencias,74991.86,110404.68,185396.54,baja al 9/12
348,20-22709722-2,2019,12,LOPEZ,MATIAS,SECR Desarrollo Ciudadano,74991.86,110404.68,185396.54,baja al 9/12
354,20-20008464-1,2019,12,GIUSTI,JOSE LUIS,UPE Transferencia de Funciones y Facultades en...,74991.86,110404.68,185396.54,baja al 9/12
358,20-31164337-2,2019,12,DI BENEDETTO,FEDERICO,SS Comunicacion,74991.86,110404.68,185396.54,baja al 9/12
360,20-28908968-4,2019,12,COELHO CHICANO,CHRISTIAN,SS Contenidos,74991.86,110404.68,185396.54,baja al 9/12
362,20-24424714-9,2019,12,D'ALESSANDRO,MARCELO SILVIO,SECR Justicia y Seguridad,74991.86,110404.68,185396.54,baja al 9/12

# Otros análisis descriptivos

Pandas viene con algunas funciones built-in para ayudar al análisis descriptivo.

## Para las variables numéricas

In [304]:
df.describe()

,anio,mes,asignacion_por_cargo_i,aguinaldo_ii,total_salario_bruto_i_+_ii
count,385.0,385.000000,385.000000,385.000000,385.000000
mean,2019.0,6.631169,234234.368000,20282.084883,254516.452883
std,0.0,3.539077,35043.160085,45248.840725,51434.987870
min,2019.0,1.000000,74991.860000,0.000000,185396.540000
25%,2019.0,4.000000,224516.620000,0.000000,224516.620000
50%,2019.0,7.000000,239470.360000,0.000000,245811.620000
75%,2019.0,10.000000,249972.870000,0.000000,263531.980000
max,2019.0,12.000000,275089.750000,170855.560000,445945.310000

## Para las variables categóricas

In [305]:
df['reparticion'].value_counts()

reparticion
SECR Desarrollo Ciudadano                                         13
Ministerio de Salud                                               13
SECR Justicia y Seguridad                                         13
SECR de Medios                                                    13
Jefe de Gobierno                                                  12
SECR Legal y Técnica                                              12
SS Contenidos                                                     12
Ente de Turismo Ley Nº 2627                                       12
Consejo de los Derechos de Niñas, Niños y Adoles - Presidencia    12
Vicejefatura de Gobierno                                          12
UPE Transferencia de Funciones y Facultades en Materia de Seg.    12
SECR Administración de Seguridad y Emergencias                    12
SECR Integración Social y Urbana                                  12
SECR Integración Social Para Personas Mayores                     12
SECR Planificación, Evaluación y Coordinación de Gestión          12
SS Comunicacion                                                   12
Ministerio de Gobierno                                            12
Ministerio de Desarrollo Urbano y Transporte                      12
Jefatura de Gabinete de Ministros                                 12
Procuración General de la Ciudad de Buenos Aires                  12
Sindicatura General de la Ciudad de Buenos Aires                  12
Ministerio de Cultura                                             12
SECR Transporte                                                   11
Ministerio de Educación e Innovación                              11
SECR Coordinación General                                         11
SECR Cultura Ciudadana y Función Pública                          11
SECR General y de Relaciones Internacionales                      11
Ministerio de Economía y Finanzas                                 11
Ministerio de Hábitat y Desarrollo Humano                         11
SECR Atención y Gestión Ciudadana                                 11
Ministerio de Ambiente y Espacio Público                          11
Ministerio de Espacio Público e Higiene Urbana                     2
SECR Ciencia, Tecnologia e Innovacion                              2
Ministerio de Desarrollo Humano y Hábitat                          2
SECR Desarrollo Urbano                                             1
Ministerio de Desarrollo Económico y Producción                    1
SECR Ambiente                                                      1
SECR Comunicación, Contenidos y Participación Ciudadana            1
SECR Atención Ciudadana y Gestión Comunal                          1
Ministerio de Educación                                            1
Ministerio de Hacienda y Finanzas                                  1
SECR Innovación y Transformación Digital                           1
SECR Transformación Cultural                                       1
SECR Transporte y Obras Públicas                                   1
SECR General y Relaciones Internacionales                          1
SECR Asuntos Estratégicos                                          1
Name: count, dtype: int64

In [306]:
df = pd.read_csv(f'{RUTA_GLOBAL}/parodesprov.csv')

In [307]:
df.isnull()#.head(10)

,OBJECTID,Codigo,Texto,Cod_Prov,Cod_CCAA,TotalParoRegistrado,PAD_1C02,PAD_1_COD_PROV,PAD_1_COD_CCAA,Shape__Area,Shape__Length,Codigop
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
16334,False,False,False,False,False,False,False,True,True,False,False,True
16335,False,False,False,False,False,False,False,True,True,False,False,True
16336,False,False,False,False,False,False,False,True,True,False,False,True
16337,False,False,False,False,False,False,False,True,True,False,False,True
16338,False,False,False,False,False,False,False,True,True,False,False,True

In [308]:
df_1 = df[df['PAD_1_COD_PROV'].notnull()].copy()
df_1.head(5)

,OBJECTID,Codigo,Texto,Cod_Prov,Cod_CCAA,TotalParoRegistrado,PAD_1C02,PAD_1_COD_PROV,PAD_1_COD_CCAA,Shape__Area,Shape__Length,Codigop
0,1,1001,Alegría-Dulantzi,1,16,184.0,2856.0,Araba/Álava,16.0,3.709269e+07,48191.568537,1.0
1,2,1002,Amurrio,1,16,766.0,10260.0,Araba/Álava,16.0,1.799114e+08,90623.621986,1.0
2,3,1003,Aramaio,1,16,18.0,1502.0,Araba/Álava,16.0,1.377066e+08,58592.914048,1.0
3,4,1004,Artziniega,1,16,110.0,1840.0,Araba/Álava,16.0,5.130078e+07,31498.524044,1.0
4,5,1006,Armiñón,1,16,12.0,234.0,Araba/Álava,16.0,2.380288e+07,33293.805036,1.0

In [309]:
# ¿Cuántos municipios tiene cada comunidad? ¿Hay alguno que no tenga CCAA asociada?
df['PAD_1_COD_PROV'].value_counts(dropna=False)

PAD_1_COD_PROV
NaN                       8214
Burgos                     371
Salamanca                  362
Barcelona                  311
Zaragoza                   293
Guadalajara                288
Navarra                    272
Valencia/València          266
Ávila                      248
Zamora                     248
Cuenca                     238
Teruel                     236
Lleida                     231
Valladolid                 225
Cáceres                    223
Girona                     221
León                       211
Segovia                    209
Toledo                     204
Huesca                     202
Palencia                   191
Tarragona                  184
Soria                      183
Madrid                     179
Rioja, La                  174
Granada                    172
Badajoz                    165
Alicante/Alacant           141
Castellón/Castelló         135
Bizkaia                    112
Sevilla                    105
Almería                    103
Málaga                     103
Ciudad Real                102
Cantabria                  102
Jaén                        97
Coruña, A                   93
Ourense                     92
Gipuzkoa                    88
Albacete                    87
Huelva                      79
Asturias                    78
Córdoba                     75
Balears, Illes              67
Lugo                        67
Pontevedra                  62
Santa Cruz de Tenerife      54
Araba/Álava                 51
Murcia                      45
Cádiz                       44
Palmas, Las                 34
Ceuta                        1
Melilla                      1
Name: count, dtype: int64

In [310]:
# ¿Cuántas CCAA hay?
len(df['Cod_CCAA'].unique())

19

In [311]:
# ¿Cuántos municipios tiene cada provincia? ¿Hay alguno que no tenga provincia asociada?
len(df['Cod_Prov'].value_counts(dropna=False))

52

In [312]:
#### Entendiendo el parámetro axis
df[df.isnull().any(axis=1)]

,OBJECTID,Codigo,Texto,Cod_Prov,Cod_CCAA,TotalParoRegistrado,PAD_1C02,PAD_1_COD_PROV,PAD_1_COD_CCAA,Shape__Area,Shape__Length,Codigop
1766,1767,10905,Pueblonuevo de Miramontes,10,11,NaN,830.0,Cáceres,11.0,3.979055e+07,34532.621933,10.0
4875,4876,31505,NaN,31,15,NaN,NaN,NaN,NaN,2.214144e+05,2086.789133,NaN
4876,4877,31508,NaN,31,15,NaN,NaN,NaN,NaN,4.379565e+04,959.013359,NaN
4877,4878,31509,NaN,31,15,NaN,NaN,NaN,NaN,2.672291e+07,35438.407224,NaN
4878,4879,31510,NaN,31,15,NaN,NaN,NaN,NaN,1.953444e+06,5920.536553,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16334,16335,50901,Biel,50,2,4.0,133.0,NaN,NaN,2.396392e+08,71731.607366,NaN
16335,16336,50902,Marracos,50,2,2.0,89.0,NaN,NaN,3.102103e+07,27441.268257,NaN
16336,16337,50903,Villamayor de Gállego,50,2,97.0,2721.0,NaN,NaN,1.627609e+08,63010.591209,NaN
16337,16338,51001,Ceuta,51,18,12438.0,84959.0,NaN,NaN,2.944199e+07,50690.387388,NaN
16338,16339,52001,Melilla,52,19,10805.0,86120.0,NaN,NaN,1.993434e+07,30499.616895,NaN

In [313]:
df[~(df.notnull().all(axis=1))]

,OBJECTID,Codigo,Texto,Cod_Prov,Cod_CCAA,TotalParoRegistrado,PAD_1C02,PAD_1_COD_PROV,PAD_1_COD_CCAA,Shape__Area,Shape__Length,Codigop
1766,1767,10905,Pueblonuevo de Miramontes,10,11,NaN,830.0,Cáceres,11.0,3.979055e+07,34532.621933,10.0
4875,4876,31505,NaN,31,15,NaN,NaN,NaN,NaN,2.214144e+05,2086.789133,NaN
4876,4877,31508,NaN,31,15,NaN,NaN,NaN,NaN,4.379565e+04,959.013359,NaN
4877,4878,31509,NaN,31,15,NaN,NaN,NaN,NaN,2.672291e+07,35438.407224,NaN
4878,4879,31510,NaN,31,15,NaN,NaN,NaN,NaN,1.953444e+06,5920.536553,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16334,16335,50901,Biel,50,2,4.0,133.0,NaN,NaN,2.396392e+08,71731.607366,NaN
16335,16336,50902,Marracos,50,2,2.0,89.0,NaN,NaN,3.102103e+07,27441.268257,NaN
16336,16337,50903,Villamayor de Gállego,50,2,97.0,2721.0,NaN,NaN,1.627609e+08,63010.591209,NaN
16337,16338,51001,Ceuta,51,18,12438.0,84959.0,NaN,NaN,2.944199e+07,50690.387388,NaN
16338,16339,52001,Melilla,52,19,10805.0,86120.0,NaN,NaN,1.993434e+07,30499.616895,NaN

In [314]:
#Descartar las filas con algun valor nulo
df.dropna(inplace=True)

In [315]:
df[~(df.notnull().all(axis=1))]

Empty DataFrame
Columns: [OBJECTID, Codigo, Texto, Cod_Prov, Cod_CCAA, TotalParoRegistrado, PAD_1C02, PAD_1_COD_PROV, PAD_1_COD_CCAA, Shape__Area, Shape__Length, Codigop]
Index: []

In [316]:
# ¡Operación vectorizada!
df['Densidad'] = (df['PAD_1C02'] / df['Shape__Area']).round(3)
df

,OBJECTID,Codigo,Texto,Cod_Prov,Cod_CCAA,TotalParoRegistrado,PAD_1C02,PAD_1_COD_PROV,PAD_1_COD_CCAA,Shape__Area,Shape__Length,Codigop,Densidad
0,1,1001,Alegría-Dulantzi,1,16,184.0,2856.0,Araba/Álava,16.0,3.709269e+07,48191.568537,1.0,0.000
1,2,1002,Amurrio,1,16,766.0,10260.0,Araba/Álava,16.0,1.799114e+08,90623.621986,1.0,0.000
2,3,1003,Aramaio,1,16,18.0,1502.0,Araba/Álava,16.0,1.377066e+08,58592.914048,1.0,0.000
3,4,1004,Artziniega,1,16,110.0,1840.0,Araba/Álava,16.0,5.130078e+07,31498.524044,1.0,0.000
4,5,1006,Armiñón,1,16,12.0,234.0,Araba/Álava,16.0,2.380288e+07,33293.805036,1.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8165,8166,50901,Biel,50,2,3.0,143.0,Zaragoza,2.0,2.396392e+08,71731.607076,50.0,0.000
8166,8167,50902,Marracos,50,2,2.0,91.0,Zaragoza,2.0,3.102103e+07,27441.268570,50.0,0.000
8167,8168,50903,Villamayor de Gállego,50,2,94.0,2753.0,Zaragoza,2.0,1.627609e+08,63010.590427,50.0,0.000
8168,8169,51001,Ceuta,51,18,12477.0,84519.0,Ceuta,18.0,2.944199e+07,50690.389444,51.0,0.003
8169,8170,52001,Melilla,52,19,10868.0,86026.0,Melilla,19.0,1.993434e+07,30499.616256,52.0,0.004

In [317]:
df['Proporcion_Paro'] =  df['TotalParoRegistrado'] / df['PAD_1C02']
df['Proporcion_Paro']

0       0.064426
1       0.074659
2       0.011984
3       0.059783
4       0.051282
          ...
8165    0.020979
8166    0.021978
8167    0.034145
8168    0.147624
8169    0.126334
Name: Proporcion_Paro, Length: 8124, dtype: float64

In [318]:
df = df.rename(columns={'Shape__Area': 'Shape_Area'})

In [319]:
mediana_area = df['Shape_Area'].median()
df.query(f'Shape_Area < {mediana_area}')['Proporcion_Paro'].mean()

0.05450009114498015

In [320]:
df.query(f'Shape_Area < @mediana_area')['Proporcion_Paro'].mean()

0.05450009114498015

## DataSetGroupBy

Veamos qué devuelve pandas cuando agrupamos un dataset por una columna:

In [321]:
a = list(df.groupby('PAD_1_COD_PROV'))
a[5]
#(valor agrupado, dataframe resultante)

('Badajoz',
      OBJECTID  Codigo                     Texto  Cod_Prov  Cod_CCAA  \
 630       631    6001                   Acedera         6        11
 631       632    6002                  Aceuchal         6        11
 632       633    6003                 Ahillones         6        11
 633       634    6004                    Alange         6        11
 634       635    6005               Albuera, La         6        11
 ..        ...     ...                       ...       ...       ...
 790       791    6161             Zarza-Capilla         6        11
 791       792    6162                 Zarza, La         6        11
 792       793    6901            Valdelacalzada         6        11
 793       794    6902  Pueblonuevo del Guadiana         6        11
 794       795    6903     Guadiana del Caudillo         6        11

      TotalParoRegistrado  PAD_1C02 PAD_1_COD_PROV  PAD_1_COD_CCAA  \
 630                 86.0     823.0        Badajoz            11.0
 631                422.0    5485.0        Badajoz            11.0
 632                 52.0     934.0        Badajoz            11.0
 633                308.0    1915.0        Badajoz            11.0
 634                194.0    2031.0        Badajoz            11.0
 ..                   ...       ...            ...             ...
 790                 35.0     347.0        Badajoz            11.0
 791                404.0    3542.0        Badajoz            11.0
 792                250.0    2782.0        Badajoz            11.0
 793                164.0    2036.0        Badajoz            11.0
 794                269.0    2544.0        Badajoz            11.0

        Shape_Area  Shape__Length  Codigop  Densidad  Proporcion_Paro
 630  1.370619e+08   63575.460120      6.0       0.0         0.104496
 631  1.036120e+08   51140.124131      6.0       0.0         0.076937
 632  3.498455e+07   30806.194755      6.0       0.0         0.055675
 633  2.638175e+08  110161.348244      6.0       0.0         0.160836
 634  4.285131e+07   28882.160129      6.0       0.0         0.095519
 ..            ...            ...      ...       ...              ...
 790  1.515160e+08   59700.180214      6.0       0.0         0.100865
 791  1.042361e+08   73528.710094      6.0       0.0         0.114060
 792  5.256868e+07   33867.997628      6.0       0.0         0.089863
 793  4.720581e+07   43267.050637      6.0       0.0         0.080550
 794  4.974424e+07   32385.252137      6.0       0.0         0.105739

 [165 rows x 14 columns])

In [322]:
#  Podemos recorrer los grupos en un loop for, 
# desempaquetando la tupla que contine el nombre del grupo
#  y el DataFrame correspondiente.
for (cod_prov, group) in df.groupby('PAD_1_COD_PROV'):
    print("provincia={0}, tamaño={1}".format(cod_prov, group.shape[0]))

provincia=Albacete, tamaño=87
provincia=Alicante/Alacant, tamaño=141
provincia=Almería, tamaño=103
provincia=Araba/Álava, tamaño=51
provincia=Asturias, tamaño=78
provincia=Badajoz, tamaño=165
provincia=Balears, Illes, tamaño=67
provincia=Barcelona, tamaño=311
provincia=Bizkaia, tamaño=112
provincia=Burgos, tamaño=371
provincia=Cantabria, tamaño=102
provincia=Castellón/Castelló, tamaño=135
provincia=Ceuta, tamaño=1
provincia=Ciudad Real, tamaño=102
provincia=Coruña, A, tamaño=93
provincia=Cuenca, tamaño=238
provincia=Cáceres, tamaño=222
provincia=Cádiz, tamaño=44
provincia=Córdoba, tamaño=75
provincia=Gipuzkoa, tamaño=88
provincia=Girona, tamaño=221
provincia=Granada, tamaño=172
provincia=Guadalajara, tamaño=288
provincia=Huelva, tamaño=79
provincia=Huesca, tamaño=202
provincia=Jaén, tamaño=97
provincia=León, tamaño=211
provincia=Lleida, tamaño=231
provincia=Lugo, tamaño=67
provincia=Madrid, tamaño=179
provincia=Melilla, tamaño=1
provincia=Murcia, tamaño=45
provincia=Málaga, tamaño=103
provincia=Navarra, tamaño=272
provincia=Ourense, tamaño=92
provincia=Palencia, tamaño=191
provincia=Palmas, Las, tamaño=34
provincia=Pontevedra, tamaño=62
provincia=Rioja, La, tamaño=174
provincia=Salamanca, tamaño=362
provincia=Santa Cruz de Tenerife, tamaño=54
provincia=Segovia, tamaño=209
provincia=Sevilla, tamaño=105
provincia=Soria, tamaño=183
provincia=Tarragona, tamaño=184
provincia=Teruel, tamaño=236
provincia=Toledo, tamaño=204
provincia=Valencia/València, tamaño=266
provincia=Valladolid, tamaño=225
provincia=Zamora, tamaño=248
provincia=Zaragoza, tamaño=293
provincia=Ávila, tamaño=248

In [323]:
# Calculen la media para cada provincia de la proporción de paro. 

for (cod_prov, group) in df.groupby('PAD_1_COD_PROV'):
    print("provincia={0}, media de paro={1}".format(cod_prov, group['Proporcion_Paro'].mean()))

provincia=Albacete, media de paro=0.10713858566560387
provincia=Alicante/Alacant, media de paro=0.07376662378228857
provincia=Almería, media de paro=0.07186639744064328
provincia=Araba/Álava, media de paro=0.04601913608875631
provincia=Asturias, media de paro=0.06755422473449564
provincia=Badajoz, media de paro=0.11096359049335525
provincia=Balears, Illes, media de paro=0.04700907407618089
provincia=Barcelona, media de paro=0.05098081879962116
provincia=Bizkaia, media de paro=0.051276205419190306
provincia=Burgos, media de paro=0.04237983801091064
provincia=Cantabria, media de paro=0.07480799327869814
provincia=Castellón/Castelló, media de paro=0.054756219005669675
provincia=Ceuta, media de paro=0.14762361125900686
provincia=Ciudad Real, media de paro=0.11188105881588194
provincia=Coruña, A, media de paro=0.06494319003298168
provincia=Cuenca, media de paro=0.06108539521547999
provincia=Cáceres, media de paro=0.1004069095090072
provincia=Cádiz, media de paro=0.1313158338754046
provincia=Córdoba, media de paro=0.08694518562478057
provincia=Gipuzkoa, media de paro=0.04320205523608764
provincia=Girona, media de paro=0.041608394342017456
provincia=Granada, media de paro=0.08344736587718796
provincia=Guadalajara, media de paro=0.04756419382306086
provincia=Huelva, media de paro=0.1052615127588619
provincia=Huesca, media de paro=0.03133443426214038
provincia=Jaén, media de paro=0.056368414701898996
provincia=León, media de paro=0.05752736702740755
provincia=Lleida, media de paro=0.034761473299855586
provincia=Lugo, media de paro=0.051197277055057305
provincia=Madrid, media de paro=0.06792829349499363
provincia=Melilla, media de paro=0.12633389905377443
provincia=Murcia, media de paro=0.08375694828658184
provincia=Málaga, media de paro=0.08968662286506862
provincia=Navarra, media de paro=0.045825705065235624
provincia=Ourense, media de paro=0.06368253501383121
provincia=Palencia, media de paro=0.04184947531137375
provincia=Palmas, Las, media de paro=0.0985149792065606
provincia=Pontevedra, media de paro=0.08779835441709853
provincia=Rioja, La, media de paro=0.035615477074871095
provincia=Salamanca, media de paro=0.06040106339964379
provincia=Santa Cruz de Tenerife, media de paro=0.10632566036436845
provincia=Segovia, media de paro=0.04048987794925944
provincia=Sevilla, media de paro=0.09842709495046596
provincia=Soria, media de paro=0.026752180467351398
provincia=Tarragona, media de paro=0.05331944435043343
provincia=Teruel, media de paro=0.03862672980255899
provincia=Toledo, media de paro=0.10307568536554097
provincia=Valencia/València, media de paro=0.06995574035701169
provincia=Valladolid, media de paro=0.04943613587248699
provincia=Zamora, media de paro=0.06317049230362833
provincia=Zaragoza, media de paro=0.038815535031993795
provincia=Ávila, media de paro=0.05731898879349622

## SeriesGroupBy

In [324]:
df.groupby('PAD_1_COD_PROV')['Proporcion_Paro'].mean()

PAD_1_COD_PROV
Albacete                  0.107139
Alicante/Alacant          0.073767
Almería                   0.071866
Araba/Álava               0.046019
Asturias                  0.067554
Badajoz                   0.110964
Balears, Illes            0.047009
Barcelona                 0.050981
Bizkaia                   0.051276
Burgos                    0.042380
Cantabria                 0.074808
Castellón/Castelló        0.054756
Ceuta                     0.147624
Ciudad Real               0.111881
Coruña, A                 0.064943
Cuenca                    0.061085
Cáceres                   0.100407
Cádiz                     0.131316
Córdoba                   0.086945
Gipuzkoa                  0.043202
Girona                    0.041608
Granada                   0.083447
Guadalajara               0.047564
Huelva                    0.105262
Huesca                    0.031334
Jaén                      0.056368
León                      0.057527
Lleida                    0.034761
Lugo                      0.051197
Madrid                    0.067928
Melilla                   0.126334
Murcia                    0.083757
Málaga                    0.089687
Navarra                   0.045826
Ourense                   0.063683
Palencia                  0.041849
Palmas, Las               0.098515
Pontevedra                0.087798
Rioja, La                 0.035615
Salamanca                 0.060401
Santa Cruz de Tenerife    0.106326
Segovia                   0.040490
Sevilla                   0.098427
Soria                     0.026752
Tarragona                 0.053319
Teruel                    0.038627
Toledo                    0.103076
Valencia/València         0.069956
Valladolid                0.049436
Zamora                    0.063170
Zaragoza                  0.038816
Ávila                     0.057319
Name: Proporcion_Paro, dtype: float64

In [325]:
df.groupby('PAD_1_COD_PROV')['Shape_Area'].sum().round(1)

PAD_1_COD_PROV
Albacete                  2.462887e+10
Alicante/Alacant          9.507244e+09
Almería                   1.385529e+10
Araba/Álava               5.558551e+09
Asturias                  2.002427e+10
Badajoz                   3.580472e+10
Balears, Illes            8.397659e+09
Barcelona                 1.389313e+10
Bizkaia                   4.160037e+09
Burgos                    2.620377e+10
Cantabria                 1.002555e+10
Castellón/Castelló        1.139656e+10
Ceuta                     2.944199e+07
Ciudad Real               3.278477e+10
Coruña, A                 1.493245e+10
Cuenca                    2.915608e+10
Cáceres                   3.358043e+10
Cádiz                     1.154687e+10
Córdoba                   2.221049e+10
Gipuzkoa                  3.757743e+09
Girona                    1.075165e+10
Granada                   2.002997e+10
Guadalajara               2.134149e+10
Huelva                    1.615329e+10
Huesca                    2.852289e+10
Jaén                      2.178012e+10
León                      2.879265e+10
Lleida                    2.209015e+10
Lugo                      1.844736e+10
Madrid                    1.390127e+10
Melilla                   1.993434e+07
Murcia                    1.825000e+10
Málaga                    1.142476e+10
Navarra                   1.779043e+10
Ourense                   1.326417e+10
Palencia                  1.476077e+10
Palmas, Las               5.250341e+09
Pontevedra                8.246811e+09
Rioja, La                 9.220822e+09
Salamanca                 2.157665e+10
Santa Cruz de Tenerife    4.370210e+09
Segovia                   1.222843e+10
Sevilla                   2.230211e+10
Soria                     1.845798e+10
Tarragona                 1.110738e+10
Teruel                    2.576417e+10
Toledo                    2.606408e+10
Valencia/València         1.811013e+10
Valladolid                1.453133e+10
Zamora                    1.897687e+10
Zaragoza                  3.093779e+10
Ávila                     1.396637e+10
Name: Shape_Area, dtype: float64

## Agregaciones múltiples

Veamos ahora quiero combinar para cada provincia, cuál es el área, cuál es la población, cuál es la media y la mediana de paro y cuántas autonomías la componen. Para esto existe la función aggregate. Aplicada sobre un DataFrameGroupBy recibe como parámetro un diccionario con las nombres de columnas como claves y el tipo de agregación a realizar como valores. Pueden ser valores únicos o listas con varios valores.

In [326]:
df.groupby('PAD_1_COD_PROV').aggregate({'Shape_Area':'sum',
                                        'PAD_1C02':'sum',
                                        'Proporcion_Paro':['mean','median','size']}).head(8)

                    Shape_Area   PAD_1C02 Proporcion_Paro
                           sum        sum            mean    median size
PAD_1_COD_PROV
Albacete          2.462887e+10   392118.0        0.107139  0.104993   87
Alicante/Alacant  9.507244e+09  1836459.0        0.073767  0.072584  141
Almería           1.385529e+10   704297.0        0.071866  0.069767  103
Araba/Álava       5.558551e+09   324126.0        0.046019  0.043350   51
Asturias          2.002427e+10  1042608.0        0.067554  0.067519   78
Badajoz           3.580472e+10   684113.0        0.110964  0.111384  165
Balears, Illes    8.397659e+09  1107220.0        0.047009  0.046549   67
Barcelona         1.389313e+10  5542680.0        0.050981  0.050098  311

In [327]:
df_agregado = df.groupby('PAD_1_COD_PROV').aggregate({'Shape_Area':'sum',
                                        'PAD_1C02':'sum',
                                        'Proporcion_Paro':['mean','median','size']})

In [328]:
df_agregado.columns

MultiIndex([(     'Shape_Area',    'sum'),
            (       'PAD_1C02',    'sum'),
            ('Proporcion_Paro',   'mean'),
            ('Proporcion_Paro', 'median'),
            ('Proporcion_Paro',   'size')],
           )

También podemos agrupar por más de una columna, usando una lista en lugar de un único valor como parámetro del groupby.

In [329]:
df['Decil_Paro'] = pd.qcut(df['Proporcion_Paro'], 10, labels=range(1,11))
df

,OBJECTID,Codigo,Texto,Cod_Prov,Cod_CCAA,TotalParoRegistrado,PAD_1C02,PAD_1_COD_PROV,PAD_1_COD_CCAA,Shape_Area,Shape__Length,Codigop,Densidad,Proporcion_Paro,Decil_Paro
0,1,1001,Alegría-Dulantzi,1,16,184.0,2856.0,Araba/Álava,16.0,3.709269e+07,48191.568537,1.0,0.000,0.064426,6
1,2,1002,Amurrio,1,16,766.0,10260.0,Araba/Álava,16.0,1.799114e+08,90623.621986,1.0,0.000,0.074659,8
2,3,1003,Aramaio,1,16,18.0,1502.0,Araba/Álava,16.0,1.377066e+08,58592.914048,1.0,0.000,0.011984,1
3,4,1004,Artziniega,1,16,110.0,1840.0,Araba/Álava,16.0,5.130078e+07,31498.524044,1.0,0.000,0.059783,6
4,5,1006,Armiñón,1,16,12.0,234.0,Araba/Álava,16.0,2.380288e+07,33293.805036,1.0,0.000,0.051282,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8165,8166,50901,Biel,50,2,3.0,143.0,Zaragoza,2.0,2.396392e+08,71731.607076,50.0,0.000,0.020979,2
8166,8167,50902,Marracos,50,2,2.0,91.0,Zaragoza,2.0,3.102103e+07,27441.268570,50.0,0.000,0.021978,2
8167,8168,50903,Villamayor de Gállego,50,2,94.0,2753.0,Zaragoza,2.0,1.627609e+08,63010.590427,50.0,0.000,0.034145,3
8168,8169,51001,Ceuta,51,18,12477.0,84519.0,Ceuta,18.0,2.944199e+07,50690.389444,51.0,0.003,0.147624,10
8169,8170,52001,Melilla,52,19,10868.0,86026.0,Melilla,19.0,1.993434e+07,30499.616256,52.0,0.004,0.126334,10

## Ordenar por columnas y limitar la cantidad de resultados

Otra forma de resolver el problema de encontrar el mayor y el menos es con el método sort_values. Este método puede recibir un valor único (nombre de columna) o una lista (con varias columnas) y un orden asc o desc. Por default el orden es asc.

Si combinamos el ordenamiento con el método head() para limitar la cantidad de resultados, podemos encontrar los N primeros.

In [330]:
# Recordemos cómo abrir la documentación de un método
df.sort_values?

Signature:
df.sort_values(
    by: 'IndexLabel',
    *,
    axis: 'Axis' = 0,
    ascending: 'bool | list[bool] | tuple[bool, ...]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'str' = 'last',
    ignore_index: 'bool' = False,
    key: 'ValueKeyFunc | None' = None,
) -> 'DataFrame | None'
Docstring:
Sort by the values along either axis.

Parameters
----------
by : str or list of str
    Name or list of names to sort by.

    - if `axis` is 0 or `'index'` then `by` may contain index
      levels and/or column labels.
    - if `axis` is 1 or `'columns'` then `by` may contain column
      levels and/or index labels.
axis : "{0 or 'index', 1 or 'columns'}", default 0
     Axis to be sorted.
ascending : bool or list of bool, default True
     Sort ascending vs. descending. Specify list for multiple sort
     orders.  If this is a list of bools, must match the length of
     the by.
inplace : bool, default False
     If True, perform operation in-place.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
     Choice of sorting algorithm. See also :func:`numpy.sort` for more
     information. `mergesort` and `stable` are the only stable algorithms. For
     DataFrames, this option is only applied when sorting on a single
     column or label.
na_position : {'first', 'last'}, default 'last'
     Puts NaNs at the beginning if `first`; `last` puts NaNs at the
     end.
ignore_index : bool, default False
     If True, the resulting axis will be labeled 0, 1, …, n - 1.
key : callable, optional
    Apply the key function to the values
    before sorting. This is similar to the `key` argument in the
    builtin :meth:`sorted` function, with the notable difference that
    this `key` function should be *vectorized*. It should expect a
    ``Series`` and return a Series with the same shape as the input.
    It will be applied to each column in `by` independently.

Returns
-------
DataFrame or None
    DataFrame with sorted values or None if ``inplace=True``.

See Also
--------
DataFrame.sort_index : Sort a DataFrame by the index.
Series.sort_values : Similar method for a Series.

Examples
--------
>>> df = pd.DataFrame({
...     'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
...     'col2': [2, 1, 9, 8, 7, 4],
...     'col3': [0, 1, 9, 4, 2, 3],
...     'col4': ['a', 'B', 'c', 'D', 'e', 'F']
... })
>>> df
  col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F

Sort by col1

>>> df.sort_values(by=['col1'])
  col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D

Sort by multiple columns

>>> df.sort_values(by=['col1', 'col2'])
  col1  col2  col3 col4
1    A     1     1    B
0    A     2     0    a
2    B     9     9    c
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D

Sort Descending

>>> df.sort_values(by='col1', ascending=False)
  col1  col2  col3 col4
4    D     7     2    e
5    C     4     3    F
2    B     9     9    c
0    A     2     0    a
1    A     1     1    B
3  NaN     8     4    D

Putting NAs first

>>> df.sort_values(by='col1', ascending=False, na_position='first')
  col1  col2  col3 col4
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F
2    B     9     9    c
0    A     2     0    a
1    A     1     1    B

Sorting with a key function

>>> df.sort_values(by='col4', key=lambda col: col.str.lower())
   col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F

Natural sort with the key argument,
using the `natsort <https://github.com/SethMMorton/natsort>` package.

>>> df = pd.DataFrame({
...    "time": ['0hr', '128hr', '72hr', '48hr', '96hr'],
...    "value": [10, 20, 30, 40, 50]
... })
>>> df
    time  value
0    0hr     10
1  128hr     20
2   72hr     30
3   48hr     40
4   96hr     50
>>> from natsort import index_natsorted
>>> df.sort_values(
...     by="time",
...     key=lambda x: np.argsort(index_natsorted(df["time"]))
... )
    time  value
0    0hr     10
3   48hr     40
2   72hr     30
4   96hr     50
1  128hr     20
File:      c:\users\lenovo\appdata\roaming\python\python310\site-packages\pandas\core\frame.py
Type:      method